---
- name: Capture Script Output
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Display something
      ansible.builtin.shell:
        cmd: ls -l
        
    - name: Execute the info.sh script
      command: "{{ playbook_dir }}/info.sh"
      register: script_output

    - name: Display the script output
      debug:
        var: script_output.stdout_lines


