---
- name: Capture Script Output
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Hardware info
      vars:
        msg: |
          RAM: {{ ansible_memtotal_mb }}
          SWAP: {{ ansible_memory_mb.swap.total }}
      debug:
        msg: "{{ msg.split('\n') }}"
        
    - name: Execute the info.sh script
      command: "{{ playbook_dir }}/info.sh"
      register: script_output

    - name: Display the script output
      debug:
        var: script_output.stdout_lines


